spring:
  application:
    name: BarberShopBack
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/barbershop
    username: postgres
    password: bahmanz
  jpa:
    hibernate:
      ddl-auto: update
jwt:
  expiration-in-millis: 1_000_000_000_000